import type { Loan } from "./types";

export function getLoanData(): Loan {
  // This would normally be fetched from an API
  return {
    _id: "67cf6594b6e88e5e0c1b221c",
    id: "67cf6594b6e88e5e0c1b221c",
    username: "riyan4",
    loan_amount: 50000,
    contract_address: "",
    loan_amount_repaid: 5126,
    no_of_installments: 24,
    installments_completed: 6,
    total_discounted_amount: null,
    status: "ongoing",
    created_at: "2025-03-10T22:20:04.089000",
    installments: [
      {
        installment_id: 1,
        installment_date: "2024-11-01T00:00:00",
        installment_paid_date: null,
        installment_status: "overdue",
        amount_paid: 0,
        amount_due: 0,
      },
      {
        installment_id: 2,
        installment_date: "2024-12-01T00:00:00",
        installment_paid_date: null,
        installment_status: "overdue",
        amount_paid: 0,
        amount_due: 0,
      },
      {
        installment_id: 3,
        installment_date: "2025-01-01T00:00:00",
        installment_paid_date: null,
        installment_status: "overdue",
        amount_paid: 0,
        amount_due: 0,
      },
      {
        installment_id: 4,
        installment_date: "2025-02-01T00:00:00",
        installment_paid_date: null,
        installment_status: "overdue",
        amount_paid: 0,
        amount_due: 0,
      },
      {
        installment_id: 5,
        installment_date: "2025-03-01T00:00:00",
        installment_paid_date: null,
        installment_status: "overdue",
        amount_paid: 0,
        amount_due: 0,
      },
      {
        installment_id: 6,
        installment_date: "2025-04-01T00:00:00",
        installment_paid_date: "2025-03-12T00:08:28.176000",
        installment_status: "paid",
        amount_paid: 2494,
        amount_due: 2494,
      },
      {
        installment_id: 7,
        installment_date: "2025-05-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 8,
        installment_date: "2025-06-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 9,
        installment_date: "2025-07-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 10,
        installment_date: "2025-08-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 11,
        installment_date: "2025-09-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 12,
        installment_date: "2025-10-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 13,
        installment_date: "2025-11-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 14,
        installment_date: "2025-12-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 15,
        installment_date: "2026-01-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 16,
        installment_date: "2026-02-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 17,
        installment_date: "2026-03-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 18,
        installment_date: "2026-04-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 19,
        installment_date: "2026-05-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 20,
        installment_date: "2026-06-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 21,
        installment_date: "2026-07-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 22,
        installment_date: "2026-08-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 23,
        installment_date: "2026-09-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
      {
        installment_id: 24,
        installment_date: "2026-10-01T00:00:00",
        installment_paid_date: null,
        installment_status: "pending",
        amount_paid: 0,
        amount_due: 2493,
      },
    ],
  }
}

